USE [ZadatakDB]
GO
/****** Object:  Table [dbo].[Proizvod]    Script Date: 10/26/2019 4:54:06 PM ******/
DROP TABLE [dbo].[Proizvod]
GO
USE [master]
GO
/****** Object:  Database [ZadatakDB]    Script Date: 10/26/2019 4:54:06 PM ******/
DROP DATABASE [ZadatakDB]
GO
/****** Object:  Database [ZadatakDB]    Script Date: 10/26/2019 4:54:06 PM ******/
CREATE DATABASE [ZadatakDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ZadatakDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\ZadatakDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ZadatakDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\ZadatakDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [ZadatakDB] SET COMPATIBILITY_LEVEL = 140
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ZadatakDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [ZadatakDB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [ZadatakDB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [ZadatakDB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [ZadatakDB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [ZadatakDB] SET ARITHABORT OFF 
GO
ALTER DATABASE [ZadatakDB] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [ZadatakDB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [ZadatakDB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [ZadatakDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [ZadatakDB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [ZadatakDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [ZadatakDB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [ZadatakDB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [ZadatakDB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [ZadatakDB] SET  DISABLE_BROKER 
GO
ALTER DATABASE [ZadatakDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [ZadatakDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [ZadatakDB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [ZadatakDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [ZadatakDB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [ZadatakDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [ZadatakDB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [ZadatakDB] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [ZadatakDB] SET  MULTI_USER 
GO
ALTER DATABASE [ZadatakDB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [ZadatakDB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [ZadatakDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [ZadatakDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [ZadatakDB] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [ZadatakDB] SET QUERY_STORE = OFF
GO
USE [ZadatakDB]
GO
/****** Object:  Table [dbo].[Proizvod]    Script Date: 10/26/2019 4:54:06 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Proizvod](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[naziv] [nvarchar](50) NOT NULL,
	[opis] [nvarchar](50) NOT NULL,
	[kategorija] [nvarchar](50) NOT NULL,
	[proizvodjac] [nvarchar](50) NOT NULL,
	[dobavljac] [nvarchar](50) NOT NULL,
	[cena] [float] NOT NULL,
 CONSTRAINT [PK_Proizvod] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET IDENTITY_INSERT [dbo].[Proizvod] ON 

INSERT [dbo].[Proizvod] ([id], [naziv], [opis], [kategorija], [proizvodjac], [dobavljac], [cena]) VALUES (1, N'2', N'1', N'1', N'1', N'1', 1)
INSERT [dbo].[Proizvod] ([id], [naziv], [opis], [kategorija], [proizvodjac], [dobavljac], [cena]) VALUES (3, N'2', N'2', N'2', N'2', N'2', 0)
SET IDENTITY_INSERT [dbo].[Proizvod] OFF
USE [master]
GO
ALTER DATABASE [ZadatakDB] SET  READ_WRITE 
GO
